//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catagorytask.Models
{
    using Microsoft.AspNetCore.Mvc;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AllCatagory_Table1
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Sno is Required")]
        public Nullable<int> Sno { get; set; }
        [Required(ErrorMessage = "Catagory is Required")]
        public string Catagory { get; set; }
        [Required(ErrorMessage = "Name is Required")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Quantity is Required")]
        public Nullable<int> Quantity { get; set; }
        [Required(ErrorMessage = "Created_on is Required")]

        
        public Nullable<System.DateTime> Created_on { get; set; }
        [Required(ErrorMessage = "Created_by is Required")]
        [DataType(DataType.Upload)]
        public string Created_by { get; set; }
        [Required(ErrorMessage = "Updated_on is Required")]

        [DataType(DataType.DateTime)]
        [BindProperty, DisplayFormat(DataFormatString = "{0:yyyy-MM-ddTHH:mm}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> Updated_on { get; set; }
        [Required(ErrorMessage = "Updated_by is Required")]
        public string Updated_by { get; set; }
        [Required(ErrorMessage = "Price is Required")]
        public Nullable<int> Price { get; set; }
        public string Status_report { get; set; }
    }
}
